export const portfolio = {
  identity: {
    name: "Lokeshprasanth Gadesula",
    shortName: "Lokesh",
    role: "Senior Software & Applied AI Engineer",
    specialties: [
      "Distributed Systems",
      "Backend Infrastructure",
      "LLM Evaluation",
      "Agentic Workflows",
    ],
    stackLine: ["Python", "Go", "Spark", "Kafka", "AWS"],
    statement: "I engineer the infrastructure behind intelligent systems.",
    alternateStatements: [
      "Distributed systems, data pipelines, and AI evaluation built to hold up in production.",
      "Event streams, backend services, and AI agents connected into dependable systems.",
    ],
    location: "United States",
    experienceYears: "6+",
    proof: [
      { value: "6+", label: "years building production systems" },
      { value: "40%", label: "lower functional regression rate" },
      { value: "Millions", label: "events processed daily" },
    ],
  },
  links: {
    website: "https://imlokesh.me",
    github: "https://github.com/lokeshgadesula",
    linkedin: "https://www.linkedin.com/in/lokeshprasanth-gadesula-701682214/",
    email: "mailto:lokeshprasanth995@gmail.com",
    resume: "/Lokeshprasanth_Gadesula.pdf",
    resumeTerminal: "/resume",
  },
  nav: [
    { label: "Overview", href: "#overview" },
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Stack", href: "#stack" },
    { label: "Lab", href: "#lab" },
    { label: "Contact", href: "#contact" },
  ],
  metrics: [
    { value: 6, suffix: "+", label: "Years Engineering Experience" },
    { value: 40, suffix: "%", label: "Regression Reduction" },
    { value: 35, suffix: "%", label: "Faster Integration Tests" },
    { value: 30, suffix: "%", label: "Higher Query Throughput" },
    { value: 25, suffix: "%", label: "Deployment Turnaround Improvement" },
    { value: 1, prefix: "<", suffix: "%", label: "Pipeline SLA Breach Rate" },
    { value: 1000, suffix: "+", label: "Synthetic Evaluation Scenarios" },
    { value: 1, suffix: "M+", label: "Events Processed Daily" },
  ],
  modules: [
    {
      id: "ai",
      index: "01",
      title: "Applied AI & LLM Systems",
      summary: "Evaluation, retrieval, agents, and telemetry brought together to make model behavior testable and traceable.",
      items: [
        "Automated evaluation benchmarks",
        "Hallucination detection",
        "Synthetic data generation",
        "RAG architectures",
        "Tool-augmented agents",
        "Structured-output validation",
        "Model telemetry",
      ],
      flow: ["PROMPT", "AGENT", "TOOL", "EVALUATOR", "TELEMETRY"],
    },
    {
      id: "data",
      index: "02",
      title: "Data & Streaming Infrastructure",
      summary: "Batch and streaming pipelines built to keep high-volume data moving, measurable, and useful.",
      items: [
        "Kafka",
        "Spark",
        "Airflow",
        "AWS Glue",
        "Redshift",
        "Athena",
        "PostgreSQL",
        "Batch + stream processing",
      ],
      flow: ["KAFKA", "SPARK", "AIRFLOW", "S3", "REDSHIFT"],
    },
    {
      id: "backend",
      index: "03",
      title: "Backend & Platform Engineering",
      summary: "Services and APIs designed for reliability, visibility, and safe change in production.",
      items: [
        "Python",
        "Go",
        "REST",
        "gRPC",
        "Async architectures",
        "Distributed services",
        "Observability",
        "Cloud-native infrastructure",
      ],
      flow: ["CLIENT", "API", "SERVICE", "QUEUE", "DATABASE"],
    },
  ],
  experience: [
    {
      build: "04",
      dates: "2025 → PRESENT",
      role: "Senior Software Engineer & AI Evaluation Specialist",
      company: "Pionner Solutions",
      achievements: [
        "Built end-to-end LLM evaluation and benchmarking frameworks that reduced functional regressions by 40%.",
        "Engineered distributed Python and AWS ECS test harnesses to evaluate reasoning, tool calls, and deterministic outputs across thousands of scenarios.",
        "Designed low-latency validation services that cut integration test execution time by 35%.",
        "Added distributed telemetry and structured logging to make inference anomalies and bottlenecks easier to trace.",
      ],
      technologies: ["Python", "AWS ECS", "LLM Evaluation", "Docker", "PostgreSQL", "Telemetry", "Distributed Systems"],
    },
    {
      build: "03",
      dates: "SEP 2023 → JUN 2025",
      role: "Full Stack & Distributed Systems Engineer",
      company: "Cybersoft Technologies",
      achievements: [
        "Built Kafka and Spark ingestion pipelines that processed millions of events each day.",
        "Developed Python REST and gRPC services backed by PostgreSQL and Redshift.",
        "Improved query throughput across services by 30%.",
        "Automated Airflow workflows and brought SLA breaches below 1%.",
        "Delivered React monitoring dashboards that made production behavior easier to see.",
      ],
      technologies: ["Python", "Kafka", "Spark", "Airflow", "PostgreSQL", "Redshift", "React", "gRPC"],
    },
    {
      build: "02",
      dates: "SEP 2021 → JUL 2023",
      role: "Frontend & Distributed Systems Engineer",
      company: "Zognu",
      achievements: [
        "Built React and TypeScript interfaces for administrative workflows.",
        "Connected Python microservices with Spark aggregation pipelines.",
        "Provisioned AWS infrastructure with Terraform.",
        "Streamlined deployments and reduced turnaround time by 25%.",
      ],
      technologies: ["React", "TypeScript", "Python", "Spark", "AWS", "Terraform"],
    },
    {
      build: "01",
      dates: "SEP 2020 → AUG 2021",
      role: "Backend & Platform Engineer",
      company: "NullClass",
      achievements: [
        "Developed Python backend services and authentication infrastructure.",
        "Improved database access through indexing and query tuning.",
        "Built AWS Lambda orchestration and CloudWatch monitoring.",
        "Automated CI/CD with GitHub Actions and Docker deployments.",
      ],
      technologies: ["Python", "AWS Lambda", "CloudWatch", "GitHub Actions", "Docker", "SQL"],
    },
  ],
  technologies: [
    { name: "Python", category: "Languages", links: ["LLM Evaluation Harness", "Kafka/Spark Platform", "Backend APIs", "AWS Automation", "Agent Systems"] },
    { name: "Go", category: "Languages", links: ["Backend APIs", "Distributed Services"] },
    { name: "C++", category: "Languages", links: ["Systems Engineering", "Inference Runtime"] },
    { name: "JavaScript", category: "Languages", links: ["Frontend Systems", "Operational Dashboards"] },
    { name: "TypeScript", category: "Languages", links: ["Frontend Systems", "Portfolio Runtime"] },
    { name: "SQL", category: "Languages", links: ["PostgreSQL", "Redshift", "Analytics"] },
    { name: "Apache Spark", category: "Data", links: ["Event Ingestion", "Aggregation", "Batch Processing"] },
    { name: "Kafka", category: "Data", links: ["Cybersoft", "Event Ingestion Engine", "Spark", "Airflow", "Redshift"] },
    { name: "Airflow", category: "Data", links: ["Workflow Orchestration", "SLA Reliability"] },
    { name: "AWS Glue", category: "Data", links: ["ETL", "Data Lake"] },
    { name: "Redshift", category: "Data", links: ["Analytics Warehouse", "Event Platform"] },
    { name: "Athena", category: "Data", links: ["S3 Analytics", "Ad-hoc Querying"] },
    { name: "PostgreSQL", category: "Data", links: ["Backend APIs", "LLM Evaluation", "Operational Data"] },
    { name: "LLM Evaluation", category: "AI", links: ["Benchmarking", "Regression Detection", "Scoring"] },
    { name: "Agentic Workflows", category: "AI", links: ["Tool Calling", "Structured Output", "Orchestration"] },
    { name: "RAG", category: "AI", links: ["Retrieval", "Reranking", "Grounded Generation"] },
    { name: "Benchmarking", category: "AI", links: ["Synthetic Scenarios", "Automated Validation"] },
    { name: "Tool Calling", category: "AI", links: ["Agents", "Validation", "Telemetry"] },
    { name: "Synthetic Data", category: "AI", links: ["Evaluation", "Coverage", "Edge Cases"] },
    { name: "Automated Telemetry", category: "AI", links: ["Inference Anomalies", "Observability"] },
    { name: "AWS S3", category: "Cloud", links: ["Data Lake", "Batch Pipelines"] },
    { name: "EMR", category: "Cloud", links: ["Spark", "Distributed Processing"] },
    { name: "ECS", category: "Cloud", links: ["Evaluation Harness", "Container Runtime"] },
    { name: "Lambda", category: "Cloud", links: ["Automation", "Event Processing"] },
    { name: "Docker", category: "Cloud", links: ["Services", "Evaluation", "CI/CD"] },
    { name: "Kubernetes", category: "Cloud", links: ["Orchestration", "Platform Engineering"] },
    { name: "Terraform", category: "Cloud", links: ["Infrastructure as Code", "AWS"] },
    { name: "GitHub Actions", category: "Cloud", links: ["CI/CD", "Deployment Automation"] },
  ],
  projects: [
    {
      id: "llm-eval",
      title: "Enterprise LLM Evaluation & Red-Teaming Harness",
      description: "I designed this evaluation harness to pressure-test LLM tool calls, structured JSON, and edge-case code generation across 1,000+ synthetic scenarios.",
      stack: ["Python", "Docker", "AWS Lambda", "PostgreSQL", "Pytest", "LangChain / LlamaIndex"],
      architecture: ["PROMPTS", "SCENARIO GENERATOR", "LLM", "TOOL EXECUTION", "VALIDATOR", "SCORING ENGINE", "TELEMETRY"],
      technical: [
        "Schema validation catches broken tool-output contracts",
        "Synthetic scenarios probe edge cases",
        "Regression scoring and telemetry trace behavior across model versions",
      ],
      github: "https://github.com/lokeshgadesula",
    },
    {
      id: "streaming",
      title: "Scalable Event-Driven Ingestion & Analytics Engine",
      description: "This streaming and batch pipeline carries Kafka events through Spark deduplication and aggregation, coordinates work in Airflow, and lands analytics in Redshift.",
      stack: ["Python", "Kafka", "Spark", "Airflow", "AWS S3", "Redshift"],
      architecture: ["PRODUCERS", "KAFKA", "SPARK STREAMING", "DEDUPLICATION", "AGGREGATION", "S3", "REDSHIFT"],
      technical: [
        "Streaming and batch paths share a coordinated data flow",
        "Distributed processing handles event deduplication and aggregation",
        "Airflow manages backfills, retries, and SLA controls",
      ],
      github: "https://github.com/lokeshgadesula",
    },
  ],
  commandPalette: [
    ["About", "#overview"],
    ["Experience", "#experience"],
    ["Projects", "#projects"],
    ["AI Systems", "#overview"],
    ["Data Infrastructure", "#overview"],
    ["Backend", "#overview"],
    ["Tech Stack", "#stack"],
    ["Contact", "#contact"],
    ["Resume", "#resume"],
  ] as const,
  targetRoles: [
    "Applied AI Engineer",
    "AI Systems Engineer",
    "Senior Backend Engineer",
    "Senior Distributed Systems Engineer",
    "Senior Data Platform Engineer",
  ],
} as const;

export type PortfolioConfig = typeof portfolio;
